/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "outline-variant": "#3a494b",
        "on-primary-fixed": "#002022",
        "surface-bright": "#3a3939",
        "on-tertiary-container": "#605f5f",
        background: "#131313",
        "secondary-container": "#ff8a00",
        "on-secondary-container": "#613100",
        "on-error-container": "#ffdad6",
        "primary-container": "#00f2ff",
        "primary-fixed-dim": "#00dbe7",
        "tertiary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#e5e2e1",
        tertiary: "#faf6f6",
        surface: "#131313",
        "on-secondary-fixed-variant": "#6f3900",
        "inverse-on-surface": "#313030",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#2f1500",
        "surface-variant": "#353534",
        "inverse-primary": "#00696f",
        "on-primary-container": "#006a71",
        "surface-container": "#201f1f",
        "on-tertiary": "#313030",
        primary: "#e1fdff",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9cacb",
        "on-secondary": "#4e2600",
        "surface-tint": "#00dbe7",
        "on-error": "#690005",
        "tertiary-container": "#dddada",
        "secondary-fixed": "#ffdcc4",
        "secondary-fixed-dim": "#ffb77f",
        outline: "#849495",
        "on-primary-fixed-variant": "#004f54",
        secondary: "#ffb77f",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "primary-fixed": "#74f5ff",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#474746",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed": "#1c1b1b",
        "on-primary": "#00363a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "gutter": "1.5rem",
        "container-padding-mobile": "1.25rem",
        "unit": "4px",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "container-padding-desktop": "2.5rem"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["'JetBrains Mono'", "monospace"]
      }
    },
  },
  plugins: [],
}
